### ISSUE TITLE
Breaking Change: Rethink Lesson Folder Organization

### ISSUE THREAD

**Issue by zkamvar** [zkamvar/sandpaper#22]
At the moment, the folders in the lesson are all organized underneath the episodes folder. This is.... not optimal because it breaks the relationship between the folder structure you see in the repository with the folder structure that you see on the website. Ideally, you would want to have the folder structure reflect the structure of the website menu. 

All of this can change, but it would be a good idea to make sure that we can switch between folder structures (heavily related to #19). 

At the moment, it would be good to have a similar structure to what we have for the current template with the flexibility and notion that it could change.

I think the idea behind this is that the folders could look like this:

```
./
|-- CONDUCT.md
|-- SETUP.md
|-- episodes/
|-- extras/
|-- something/ 
|   `-- hidden/
`- LICENSE.md
```

The issue with this is how you tell {sandpaper} that this is the configuration you want without getting too in the weeds with yaml files. Why, you ask? Because I want to avoid behemoth config files that look like this: https://github.com/grunwaldlab/Population_Genetics_in_R/blob/master/_site.yml 

It _might_ be possible to do something like this, but it might be too complex :grimacing: 

```yaml
- episodes
  path: episodes/
  order:
  - introduction.md
  - getting-to-know-vectors.Rmd
- extras
  path: extras/
  order:
  - factors.Rmd
  - classes.Rmd
- hidden
  path: something/hidden/
  order:
  - hidden-extra.md
```
